#this file is mostly copied from https://docs.travis-ci.com/user/languages/python/
#it contains the information for automated testing on Github

#this is a python project, designed to be compatible with 3.6+
language: python

# cache pip
cache:
  directories:
    - $HOME/.cache/pip #linux
    - $HOME/Library/Caches/pip #macosx
    - $HOME/AppData/Local/pip/Cache #windows
    - $HOME/upx #upx

#default VM settings
dist: bionic
python: "3.7"
env:
  global:
    - PYTHON_EXECUTABLE="python"
    - UPX_VERSION="3.95"

# cache
# before_install
# install
### jobs ###
# before_script
# script
# before_cache
# after_success
# before_deploy
# deploy
# after_deploy

# upgrade pip
# install pillow, numpy for app
# install pyinstaller for distilling
install:
  - pip install -U wheel
  - pip install -r "./app_resources/meta/manifests/pip_requirements.txt"
  - export DEPLOY=yes

# get UPX
# negated in Test Phase
# negated in Xenial
before_script: ./scripts/get_upx.sh

jobs:
  include:
    # 3.7 on Bionic Test
    - &tests
      stage: "Unit Tests"
      name: "Python 3.7 on Ubuntu Bionic: Test"
      dist: bionic
      python: "3.7"
      services: xvfb
      before_script: echo "#do nothing before script"
      script: ${PYTHON_EXECUTABLE} tests.py

    # 3.7 on Bionic Build/Deploy
    - &build-deploy
      stage: "Build & Deploy Binaries"
      name: "3.7 on Bionic: Build/Deploy"
      dist: bionic
      python: "3.7"
      services: xvfb
      skip_cleanup: true
      script:
        #run build script
        #list files to see what was built
        - ${PYTHON_EXECUTABLE} build.py
        - ls
      after_success: ./scripts/after_success.sh
      deploy:
        provider: releases
        api_key:
          secure: $GITHUB_DEPLOY_KEY
        file_glob: true
        file: $FILES_TO_UPLOAD
        skip_cleanup: true
        on:
          repo: Artheau/SpriteSomething
          condition: $DEPLOY == "yes"
          branch: master
          draft: true

    # 3.7 on Xenial
    - <<: *tests
      name: "Python 3.7 on Ubuntu Xenial: Test"
      dist: xenial
      python: "3.7"
      services: xvfb
    - <<: *build-deploy
      name: "3.7 on Xenial: Build/No Deploy"
      dist: xenial
      python: "3.7"
      services: xvfb
      before_script: ./scripts/deploy_no.sh

    # 3.6 on Xenial
    - <<: *tests
      name: "Python 3.6 on Ubuntu Xenial: Test"
      dist: xenial
      python: "3.6"
      services: xvfb
    - <<: *build-deploy
      name: "3.6 on Xenial: Build/No Deploy"
      dist: xenial
      python: "3.6"
      services: xvfb
      before_script: ./scripts/deploy_no.sh

    # 3.7 on macOS
    - <<: *tests
      name: "Python 3.7 on MacOSX 10.14 xcode 10.2: Test"
      os: osx
      osx_image: xcode10.2
      python: "3.7"
      services:
      language: shell
      before_install:
        - export PYTHON_EXECUTABLE=python3
    - <<: *build-deploy
      name: "3.7 on MacOSX: Build/Deploy"
      os: osx
      osx_image: xcode10.2
      python: "3.7"
      services:
      language: shell
      before_install:
        - export PYTHON_EXECUTABLE=python3

    # 3.7 on Windows
    - <<: *tests
      name: "Python 3.7 on Windows 10 v1803: Test"
      os: windows
      python: "3.7"
      services: xvfb
      language: shell
      before_install: ./scripts/win-before_install.sh
    - <<: *build-deploy
      name: "3.7 on Windows: Build/Deploy"
      os: windows
      python: "3.7"
      services: xvfb
      language: shell
      before_install: ./scripts/win-before_install.sh

notifications:
  email: false
