#this file is mostly copied from https://docs.travis-ci.com/user/languages/python/
#it contains the information for automated testing on Github

#this is a python project, designed to be compatible with 3.6+
language: python

#default VM settings
python: 3.7
dist: bionic
env: PYTHON_EXECUTABLE="python"

#define UPX version
env: UPX_VERSION=3.95

# get UPX
#before_install:
#  - wget https://github.com/upx/upx/releases/download/v{$UPX_VERSION}/upx-${UPX_VERSION}-amd64_linux.tar.gz
#  - sudo tar -C /usr/local -xf upx-${UPX_VERSION}-amd64_linux.tar.gz
#  - mv /usr/local/upx-${UPX_VERSION}-amd64_linux/ ./upx/

# upgrade pip
# install pillow, numpy for app
# install pyinstaller for distilling
install:
  - pip3 install --upgrade pip
  - pip install pillow numpy pyinstaller

# create Unit Testing alias
tests: &tests
  - stage: "Tests"
    name: "Unit Testing"

    # Linux needs a "screen" for tkinter
    script:
      - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
          export DISPLAY=:99.0;
          sh -e /etc/init.d/xvfb start;
          sleep 3;
          fi
      - $PYTHON_EXECUTABLE tests.py

# create Build alias
build: &build
  - stage: "Build"
    name: "Build Binaries"
    skip_cleanup: true
    script:
      - $PYTHON_EXECUTABLE build.py
      - ls

jobs:
  include:
    # 3.7 on Bionic
    - <<: *tests
      name: "3.7 on Bionic: Test"
    - <<: *build
      name: "3.7 on Bionic: Build"

    # 3.7 on Xenial
    - <<: *tests
      name: "3.7 on Xenial: Test"
      dist: xenial
    - <<: *build
      name: "3.7 on Xenial: Build"
      dist: xenial

    # 3.6 on Xenial
    - <<: *tests
      name: "3.6 on Xenial: Test"
      python: 3.6
      dist: xenial
    - <<: *build
      name: "3.6 on Xenial: Build"
      python: 3.6
      dist: xenial

    # 3.7 on macOS
    - <<: *tests
      name: "3.7 on macOS: Test"
      os: osx
      osx_image: xcode10.2
      language: shell
      env: PYTHON_EXECUTABLE="python3"
    - <<: *build
      name: "3.7 on macOS: Build"
      os: osx
      osx_image: xcode10.2
      language: shell
      env: PYTHON_EXECUTABLE="python3"

    # 3.7 on Windows
    - <<: *tests
      name: "3.7 on Windows: Test"
      os: windows
      language: shell
      before_install:
        - choco install python
        - python -m pip install --upgrade pip
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
    - <<: *build
      name: "3.7 on Windows: Build"
      os: windows
      language: shell
      before_install:
        - choco install python
        - python -m pip install --upgrade pip
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH

deploy:
  provider: releases
  api_key:
    secret: $GITHUB_TOKEN_mm1
  file_glob: true
  file: /^(.\/)?(\w)*(.exe|$)/gm
  skip_cleanup: true
  on:
    repo: Artheau/SpriteSomething
    branch: standardize
#    python: 3.7
#    tags: true
    draft: true

notifications:
  email: false
