#this file is mostly copied from https://docs.travis-ci.com/user/languages/python/
#it contains the information for automated testing on Github

#this is a python project, designed to be compatible with 3.6+
language: python

#default VM settings
dist: bionic
python: 3.7
env:
  global:
    - PYTHON_EXECUTABLE="python"
    - UPX_VERSION=3.95

# get UPX
#before_install:
#  - wget https://github.com/upx/upx/releases/download/v{$UPX_VERSION}/upx-${UPX_VERSION}-amd64_linux.tar.gz
#  - sudo tar -C /usr/local -xf upx-${UPX_VERSION}-amd64_linux.tar.gz
#  - mv /usr/local/upx-${UPX_VERSION}-amd64_linux/ ./upx/

# upgrade pip
# install pillow, numpy for app
# install pyinstaller for distilling
install:
  - pip3 install --upgrade pip
  - pip install pillow numpy pyinstaller

jobs:
  include:
    # 3.7 on Bionic Test
    - &tests
      stage: "Unit Tests"
      name: "3.7 on Bionic: Test"
      dist: bionic
      python: 3.7
      services: xvfb
      script: ${PYTHON_EXECUTABLE} tests.py

    # 3.7 on Bionic Build
    - &build
      stage: "Build Binaries"
      name: "3.7 on Bionic: Build"
      dist: bionic
      python: 3.7
      services: xvfb
      skip_cleanup: true
      script:
        - ${PYTHON_EXECUTABLE} build.py
        - ls
        - ls -p | egrep '^(.\/)?(\w)*(.exe|$)'

    # Deploy
    - &deploy-github-releases
      stage: "Deploy to GitHub Releases"
      name: "Deploy"
      deploy:
        provider: releases
        api_key:
          secure: $GITHUB_TOKEN_mm1
        file_glob: true
        file: /^(.\/)?(\w)*(.exe|$)/gm
        skip_cleanup: true
        on:
          repo: Artheau/SpriteSomething
          branch: master
#          branch: standardize
          python: 3.7
#          tags: true
          draft: true

    # 3.7 on Xenial
    - <<: *tests
      name: "3.7 on Xenial: Test"
      dist: xenial
      python: 3.7
    - <<: *build
      name: "3.7 on Xenial: Build"
      dist: xenial
      python: 3.7

    # 3.6 on Xenial
    - <<: *tests
      name: "3.6 on Xenial: Test"
      dist: xenial
      python: 3.6
    - <<: *build
      name: "3.6 on Xenial: Build"
      dist: xenial
      python: 3.6

    # 3.7 on macOS
    - <<: *tests
      name: "3.7 on macOS: Test"
      os: osx
      osx_image: xcode10.2
      python: 3.7
      language: shell
      before_script:
        - export PYTHON_EXECUTABLE=python3
    - <<: *build
      name: "3.7 on macOS: Build"
      os: osx
      osx_image: xcode10.2
      python: 3.7
      language: shell
      before_script:
        - export PYTHON_EXECUTABLE=python3

    # 3.7 on Windows
    - <<: *tests
      name: "3.7 on Windows: Test"
      os: windows
      python: 3.7
      language: shell
      before_install:
        - choco install python
        - export PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        - ${PYTHON_EXECUTABLE} get-pip.py
        - ${PYTHON_EXECUTABLE} -m pip install --upgrade pip
    - <<: *build
      name: "3.7 on Windows: Build"
      os: windows
      python: 3.7
      language: shell
      before_install:
        - choco install python
        - export PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        - ${PYTHON_EXECUTABLE} get-pip.py
        - ${PYTHON_EXECUTABLE} -m pip install --upgrade pip

notifications:
  email: false
