# workflow name
name: CI Lite

# fire on
on: [ push, pull_request ]

# stuff to do
jobs:
  # Install & Test
  #  Set up environment
  # Test
  #  Run tests/tests.py
  install-test:
    name: Install/Test
    # cycle through os list
    runs-on: ${{ matrix.os-name }}
    # VM settings
    #  os & python versions
    strategy:
      matrix:
        os-name: [ ubuntu-latest, ubuntu-16.04, macOS-latest ]
        python-version: [ 3.7 ]
    steps:
    # checkout commit
    - name: Checkout commit
      uses: actions/checkout@v1
    # install python
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    # install dependencies via pip
    - name: Install Dependencies via pip
      env:
        OS_NAME: ${{ matrix.os-name }}
      run: |
        python ./resources/ci/common/install.py
    # run tests
    - name: Run Tests
      run: |
        python ./tests/tests.py
