# workflow name
name: Test, Build, Deploy Release, Deploy Pages

# fire on
on: [ push, pull_request ]

########################
# Non-GitHub providers #
########################
# deploy-release: docker://softprops/action-gh-release
# deploy-pages:   peaceiris/actions-gh-pages@v1.1.0

# stuff to do
jobs:
  # Installation
  #  Set up environment
  #   Windows uses pip
  #   Linux/Mac uses pip3
  #   Windows/Linux uses python
  #   Mac uses python3
  install:
    name: Installation
    # cycle through os list
    runs-on: ${{ matrix.os-name }}

    # VM settings
    #  os & python versions
    strategy:
      matrix:
        os-name: [ ubuntu-latest, ubuntu-16.04, macOS-latest, windows-latest ]
        python-version: [ 3.7 ]
        include:
          - os-name: ubuntu-16.04
            python-version: [ 3.6, 3.7 ]

    steps:
    # install python
    - env:
      PYTHON_EXECUTABLE: python
      PIP_EXECUTABLE: pip
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: "x64"
    - run: |
        ${PYTHON_EXECUTABLE} --version
    # install dependencies via pip
    - name: Install Dependencies via pip
      run: |
        ${PYTHON_EXECUTABLE} -m pip install --upgrade pip
        ${PIP_EXECUTABLE} --version
        ${PIP_EXECUTABLE} install -r app_resources/meta/manifests/pip_requirements.txt
        apt-get install archiver

  # Unit Tests
  #  Checkout commit, run tests.py
  test:
    name: Unit Tests
    runs-on: ${{ matrix.os-name }}
    # runs after install job
    needs: [ install ]
    steps:
    - name: Checkout commit
      uses: actions/checkout@v1
    - name: Run Unit Test Package
      run: |
        ${PYTHON_EXECUTABLE} tests.py

  # Build Binary
  #  Run build.py
  build:
    name: Build Binaries
    runs-on: ${{ matrix.os-name }}
    # runs after test job
    needs: [ test ]
    steps:
    - name: Build Binary
      run: |
        ${PYTHON_EXECUTABLE} build.py

  # Prepare for Deployment to GitHub Releases
  #  Run custom action
  prepare-release:
    name: Prepare for GitHub Releases
    runs-on: ${{ matrix.os-name }}

    # VM settings
    #  os & python versions
    strategy:
      matrix:
        # don't build on python 3.6 or xenial
        os-name: [ ubuntu-latest, ubuntu-16.04, macOS-latest, windows-latest ]
        python-version: [ "3.6", "3.7" ]
        exclude:
          - os-name: ubuntu-16.04
          - python-version: "3.6"

    needs: [ build ]
    steps:
    - name: Local Prepare GitHub Release Action
      uses: ./.github/actions/prepare-release

  # Deploy to GitHub Releases
  #  Release Name:  SpriteSomethin v${GITHUB_TAG}
  #  Release Body:  Inline content of RELEASENOTES.md
  #  Release Body:  Fallback to URL to RELEASENOTES.md
  #  Release Files: ${FILES}
#  deploy-release:
#    name: Deploy to GitHub Releases
#    runs-on: ${{ matrix.os-name }}

    # VM settings
    #  os & python versions
#    strategy:
#      matrix:
        # don't build on python 3.6 or xenial
#        os-name: [ ubuntu-latest, ubuntu-16.04, macOS-latest, windows-latest ]
#        python-version: [ "3.6", "3.7" ]
#        exclude:
#          - os-name: ubuntu-16.04
#          - python-version: "3.6"

#    needs: [ prepare-release ]
#    steps:
#    - name: Create a Release
#      uses: docker://softprops/action-gh-release
#      with:
#        name: ${RELEASE_NAME}
#        draft: true
#        body: "Please see [RELEASENOTES.md](https://github.com/${GITHUB_REPOSITORY}/blog/${GITHUB_TAG}/RELEASENOTES.md) for description."
#        body_path: ${GITHUB_WORKSPACE}/RELEASENOTES.md
#        files: ${FILES}
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Prepare for Deployment to GitHub Pages
  #  run custom action
#  prepare-pages:
#    name: Prepare for GitHub Pages
#    runs-on: windows-latest
#    python-version: "3.7"
#    needs: [ deploy-release ]
#    steps:
#    - name: Local Prepare GitHub Pages Action
#      uses: ./.github/actions/prepare-pages

  # Deploy to GitHub Pages
  #
#  deploy-pages:
#    name: Deploy to GitHub Pages
#    runs-on: windows-latest
#    python-version: "3.7"
#    needs: [ prepare-pages ]
#    steps:
#      - name: Post to GitHub Pages
#        uses: peaceiris/actions-gh-pages@v1.1.0
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          PUBLISH_BRANCH: gh-pages
#          PUBLISH_DIR: ${PAGES}
