# workflow name
name: Install

# fire on
on:
  workflow_call:
    input:
      os-name:
        type: string
        required: true
        description: OS to run on
      python-version:
        type: string
        required: true
        description: Python version to install
      pillow-version:
        type: string
        required: true
        description: Pillow version to install

# actions
# actions/checkout@v3
# actions/setup-python@v3

jobs:
  install:
    name: Install
    runs-on: ${{ inputs.os-name }}

    steps:
      # checkout commit
      - name: Checkout commit
        uses: actions/checkout@v3
      # install python
      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs.python-version }}
      # install dependencies via pip
      - name: Install Dependencies via pip
        env:
          OS_NAME: ${{ inputs.os-name }}
        run: |
          python ./resources/ci/common/install.py
      - name: Install Pillow
        run: |
          python -m pip install pillow==${{ inputs.pillow-version }}
