# workflow name
name: New CI

# fire on
on: [push, pull_request]

#########
# actions
#########
# actions/checkout@v3.0.0
# actions/download-artifact@v3.0.0
# actions/create-release
# actions/upload-release-asset
# Artheau/SpriteSomething/get-parent-dir
# Artheau/SpriteSomething/install
# Artheau/SpriteSomething/test

jobs:
  # Test
  install-test:
    name: 💿/⏱️
    runs-on: ${{ matrix.os-name }}
    continue-on-error: True

    strategy:
      matrix:
        # should run on all OS
        os-name: [
          ubuntu-latest,
          ubuntu-18.04,
          macOS-latest,
          windows-latest
        ]

        # should run on py 3.8-3.10
        python-version: [
          3.8,
          3.9,
          "3.10"
        ]

        # PIL 6.2.2 is good
        # PIL 7.0.0+ introduces color error
        pillow-version:
          [
            "6.2.2",
            # "7.0.0",
            # "7.1.2",
            # "7.2.0",
            # "8.0.1",
            # "8.1.2",
            # "8.2.0",
            # "8.3.2",
            # "8.4.0",
            # "9.0.1",
          ]
        exclude:
          - os-name: macOS-latest
            python-version: 3.9
          - os-name: macOS-latest
            python-version: "3.10"
          - os-name: windows-latest
            python-version: 3.9
          - os-name: windows-latest
            python-version: "3.10"
    steps:
      # checkout commit
      - name: Checkout commit
        uses: actions/checkout@v3.0.0
      # install
      # - name: Call Install
      #   uses: ./.github/actions/install
      #   with:
      #     os-name: ${{ matrix.os-name }}
      #     python-version: ${{ matrix.python-version }}
      #     pillow-version: ${{ matrix.pillow-version }}
      # test
      # - name: Call Test
      #   uses: ./.github/actions/test
      #   with:
      #     os-name: ${{ matrix.os-name }}
      #     python-version: ${{ matrix.python-version }}
      #     pillow-version: ${{ matrix.pillow-version }}

  # Build
  install-build:
    name: 💿/🔨
    runs-on: ${{ matrix.os-name }}
    needs: [install-test]
    continue-on-error: True

    strategy:
      matrix:
        # should run on all OS
        os-name: [
          ubuntu-latest,
          ubuntu-18.04,
          macOS-latest,
          windows-latest
        ]

        # should run on py 3.8-3.10
        python-version: [
          3.8,
          3.9,
          "3.10"
        ]

        # PIL 6.2.2 is good
        # PIL 7.0.0+ introduces color error
        pillow-version:
          [
            "6.2.2",
            # "7.0.0",
            # "7.1.2",
            # "7.2.0",
            # "8.0.1",
            # "8.1.2",
            # "8.2.0",
            # "8.3.2",
            # "8.4.0",
            # "9.0.1",
          ]
        exclude:
          # mac & windows fail on 3.9+
          - os-name: macOS-latest
            python-version: 3.9
          - os-name: macOS-latest
            python-version: "3.10"
          - os-name: windows-latest
            python-version: 3.9
          - os-name: windows-latest
            python-version: "3.10"
    steps:
      # checkout commit
      - name: Checkout commit
        uses: actions/checkout@v3.0.0
      # install
      - name: Call Install
        uses: ./.github/actions/install
        with:
          os-name: ${{ matrix.os-name }}
          python-version: ${{ matrix.python-version }}
          pillow-version: ${{ matrix.pillow-version }}
      # build
      - name: Call Build
        uses: ./.github/actions/build
        with:
          os-name: ${{ matrix.os-name }}
          python-version: ${{ matrix.python-version }}
          pillow-version: ${{ matrix.pillow-version }}

  # Prepare Release
  install-release-prepare:
    name: 💿/📀->📦
    runs-on: ${{ matrix.os-name }}
    needs: [install-build]

    strategy:
      matrix:
        # should run on all LATEST OS
        os-name: [
          ubuntu-latest,
          macOS-latest,
          windows-latest
        ]

        # run on py 3.8 (EOL: 2024-10-14)
        # EOL
        #  3.8:   2024-10-14
        #  3.9:   2025-10-05
        #  3.10:  2026-10-04
        python-version: [3.8]

        # run on PIL 6.2.2
        # can't build on py 3.9-3.10
        pillow-version: ["6.2.2"]
    steps:
      # checkout commit
      - name: Checkout commit
        uses: actions/checkout@v3.0.0
      # install
      - name: Call Install
        uses: ./.github/actions/install
        with:
          os-name: ${{ matrix.os-name }}
          python-version: ${{ matrix.python-version }}
          pillow-version: ${{ matrix.pillow-version }}
      # prepare release
      - name: Prepare Release
        uses: ./.github/actions/release-prepare
        with:
          os-name: ${{ matrix.os-name }}
          python-version: ${{ matrix.python-version }}
          pillow-version: ${{ matrix.pillow-version }}

  # Deploy Release
  release-deploy:
    name: 📀->🚀
    runs-on: ${{ matrix.os-name }}
    needs: [install-release-prepare]

    strategy:
      matrix:
        os-name: [ubuntu-latest]
        python-version: [3.8]

    steps:
      # checkout commit
      - name: Checkout commit
        uses: actions/checkout@v3.0.0

      # install dependencies via pip
      - name: Install Dependencies via pip
        shell: bash
        run: |
          python -m pip install pytz requests

      # get parent dir
      - name: Get Parent Dir
        uses: ./.github/actions/get-parent-dir

      # download appversion artifact
      - name: Download AppVersion Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: appversion-${{ matrix.os-name }}
          path: ${{ steps.parentDir.outputs.value }}/build

      # download ubuntu archive artifact
      - name: Download Ubuntu Archive Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: archive-ubuntu-latest
          path: ${{ steps.parentDir.outputs.value }}/deploy/linux

      # download macos archive artifact
      # - name: Download MacOS Archive Artifact
      #   uses: actions/download-artifact@v3.0.0
      #   with:
      #     name: archive-macos-latest
      #     path: ${{ steps.parentDir.outputs.value }}/deploy/macos

      # download windows archive artifact
      - name: Download Windows Archive Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: archive-windows-latest
          path: ${{ steps.parentDir.outputs.value }}/deploy/windows

      # debug info
      - name: Debug Info
        id: debug_info
        run: |
          GITHUB_TAG="$(head -n 1 ../build/app_version.txt)"
          echo "::set-output name=github_tag::$GITHUB_TAG"
          GITHUB_TAG="v${GITHUB_TAG}"
          RELEASE_NAME="SpriteSomething ${GITHUB_TAG}"
          echo "Release Name: ${RELEASE_NAME}"
          echo "Git Tag:      ${GITHUB_TAG}"

      # create a release
      - name: Create a Release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.debug_info.outputs.github_tag }}
          release_name: SpriteSomething v${{ steps.debug_info.outputs.github_tag }}
          body_path: RELEASENOTES.md
          draft: true
        # if: contains(github.ref, 'master')

      # upload linux archive asset
      - name: Upload Linux Archive Asset
        id: upload-linux-asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ../deploy/linux/SpriteSomething.tar.gz
          asset_name: SpriteSomething-${{ steps.debug_info.outputs.github_tag }}-linux-focal.tar.gz
          asset_content_type: application/gzip
        # if: contains(github.ref, 'master')

      # upload macos archive asset
      # - name: Upload MacOS Archive Asset
      #   id: upload-macos-asset
      #   uses: actions/upload-release-asset@v1.0.2
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ../deploy/macos/SpriteSomething.tar.gz
      #     asset_name: SpriteSomething-${{ steps.debug_info.outputs.github_tag }}-osx.tar.gz
      #     asset_content_type: application/gzip
      #   if: contains(github.ref, 'master')

      # upload windows archive asset
      - name: Upload Windows Archive Asset
        id: upload-windows-asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ../deploy/windows/SpriteSomething.zip
          asset_name: SpriteSomething-${{ steps.debug_info.outputs.github_tag }}-windows.zip
          asset_content_type: application/zip
        # if: contains(github.ref, 'master')

  # Prepare Pages
  pages-prepare:
    name: 🌎->📦
    runs-on: ubuntu-latest
    needs: [release-deploy]

    steps:
      # checkout commit
      - name: Checkout commit
        uses: actions/checkout@v3.0.0
      # download appversion artifact
      - name: Download AppVersion Artifact
        uses: actions/download-artifact@v3.0.0

  # Deploy Pages
  pages-deploy:
    name: 🌎->🚀
    runs-on: ubuntu-latest
    needs: [pages-prepare]

    steps:
      # checkout commit
      - name: Checkout commit
        uses: actions/checkout@v3.0.0
