# workflow name
name: New CI

# fire on
on: [push, pull_request]

# actions
# Artheau/SpriteSomething/.github/actions/install
# Artheau/SpriteSomething/.github/actions/test

jobs:
  # Test
  install-test:
    name: 💿/⏱️
    runs-on: ${{ matrix.os-name }}
    continue-on-error: True

    strategy:
      matrix:
        # should run on all OS
        os-name: [
          ubuntu-latest,
          ubuntu-18.04,
          macOS-latest,
          windows-latest
        ]

        # should run on py 3.8-3.10
        python-version: [
          3.8,
          3.9,
          "3.10"
        ]

        # PIL 6.2.2 is good
        # PIL 7.0.0+ introduces color error
        pillow-version:
          [
            "6.2.2",
            # "7.0.0",
            # "7.1.2",
            # "7.2.0",
            # "8.0.1",
            # "8.1.2",
            # "8.2.0",
            # "8.3.2",
            # "8.4.0",
            # "9.0.1",
          ]
        exclude:
          - os-name: macOS-latest
            python-version: 3.9
          - os-name: macOS-latest
            python-version: "3.10"
          - os-name: windows-latest
            python-version: 3.9
          - os-name: windows-latest
            python-version: "3.10"
    steps:
      # checkout commit
      - name: Checkout commit
        uses: actions/checkout@v3
      # install
      # - name: Call Install
      #   uses: ./.github/actions/install
      #   with:
      #     os-name: ${{ matrix.os-name }}
      #     python-version: ${{ matrix.python-version }}
      #     pillow-version: ${{ matrix.pillow-version }}
      # test
      # - name: Call Test
      #   uses: ./.github/actions/test
      #   with:
      #     os-name: ${{ matrix.os-name }}
      #     python-version: ${{ matrix.python-version }}
      #     pillow-version: ${{ matrix.pillow-version }}

  # Build
  install-build:
    name: 💿/🔨
    runs-on: ${{ matrix.os-name }}
    needs: [install-test]
    continue-on-error: True

    strategy:
      matrix:
        # should run on all OS
        os-name: [
          ubuntu-latest,
          ubuntu-18.04,
          macOS-latest,
          windows-latest
        ]

        # should run on py 3.8-3.10
        python-version: [
          3.8,
          3.9,
          "3.10"
        ]

        # PIL 6.2.2 is good
        # PIL 7.0.0+ introduces color error
        pillow-version:
          [
            "6.2.2",
            # "7.0.0",
            # "7.1.2",
            # "7.2.0",
            # "8.0.1",
            # "8.1.2",
            # "8.2.0",
            # "8.3.2",
            # "8.4.0",
            # "9.0.1",
          ]
        exclude:
          # mac & windows fail on 3.9+
          - os-name: macOS-latest
            python-version: 3.9
          - os-name: macOS-latest
            python-version: "3.10"
          - os-name: windows-latest
            python-version: 3.9
          - os-name: windows-latest
            python-version: "3.10"
    steps:
      # checkout commit
      - name: Checkout commit
        uses: actions/checkout@v3
      # install
      - name: Call Install
        uses: ./.github/actions/install
        with:
          os-name: ${{ matrix.os-name }}
          python-version: ${{ matrix.python-version }}
          pillow-version: ${{ matrix.pillow-version }}
      # build
      - name: Call Build
        uses: ./.github/actions/build
        with:
          os-name: ${{ matrix.os-name }}
          python-version: ${{ matrix.python-version }}
          pillow-version: ${{ matrix.pillow-version }}

  # Prepare Release
  install-release-prepare:
    name: 💿/📀->📦
    runs-on: ${{ matrix.os-name }}
    needs: [install-build]

    strategy:
      matrix:
        # should run on all LATEST OS
        os-name: [
          ubuntu-latest,
          macOS-latest,
          windows-latest
        ]

        # run on py 3.8 (EOL: 2024-10-14)
        # EOL
        #  3.8:   2024-10-14
        #  3.9:   2025-10-05
        #  3.10:  2026-10-04
        python-version: [3.8]

        # run on PIL 6.2.2
        # can't build on py 3.9-3.10
        pillow-version: ["6.2.2"]
    steps:
      # checkout commit
      - name: Checkout commit
        uses: actions/checkout@v3
      # install
      - name: Call Install
        uses: ./.github/actions/install
        with:
          os-name: ${{ matrix.os-name }}
          python-version: ${{ matrix.python-version }}
          pillow-version: ${{ matrix.pillow-version }}
      # prepare release
      - name: Prepare Release
        uses: ./.github/actions/release-prepare
        with:
          os-name: ${{ matrix.os-name }}
          python-version: ${{ matrix.python-version }}
          pillow-version: ${{ matrix.pillow-version }}

  # Deploy Release
  release-deploy:
    name: 📀->🚀
    runs-on: ubuntu-latest
    needs: [install-release-prepare]
    steps:
      # checkout commit
      - name: Checkout commit
        uses: actions/checkout@v3

  # Prepare Pages
  pages-prepare:
    name: 🌎->📦
    runs-on: ubuntu-latest
    needs: [release-deploy]

    steps:
      # checkout commit
      - name: Checkout commit
        uses: actions/checkout@v3

  # Deploy Pages
  pages-deploy:
    name: 🌎->🚀
    runs-on: ubuntu-latest
    needs: [pages-prepare]

    steps:
      # checkout commit
      - name: Checkout commit
        uses: actions/checkout@v3
