# workflow name
name: New CI

# fire on
on: [ push, pull_request ]

# actions
# Artheau/SpriteSomething/.github/workflows/install.yml

jobs:
  install-test:
    name: Install/Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os-name: [ ubuntu-latest ]
    steps:
      - name: Call Install
        uses: ./.github/actions/install
        with:
          os-name: ${{ matrix.os-name }}
          python-version: ${{ matrix.python-version }}
          pillow-version: ${{ matrix.pillow-version }}
