# workflow name
name: New CI

# fire on
on: [push, pull_request]

# actions
# Artheau/SpriteSomething/.github/actions/install
# Artheau/SpriteSomething/.github/actions/test

jobs:
  install-test:
    name: Install/Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os-name: [
            # ubuntu-latest,
            # ubuntu-18.04,
            # macOS-latest,
            # windows-latest

            ubuntu-latest, # testing OS
          ]
        python-version: [
            3.8,
            # 3.9,
            "3.10",
          ]
        pillow-version: [
            "6.2.2",
            # "7.0.0",
            # "7.1.2",
            # "7.2.0",
            # "8.0.1",
            # "8.1.2",
            # "8.2.0",
            # "8.3.2",
            # "8.4.0",
            "9.0.1",
          ]
    steps:
      # checkout commit
      - name: Checkout commit
        uses: actions/checkout@v3
      # install
      - name: Call Install
        uses: ./.github/actions/install
        with:
          os-name: ${{ matrix.os-name }}
          python-version: ${{ matrix.python-version }}
          pillow-version: ${{ matrix.pillow-version }}
      # test
      - name: Call Test
        uses: ./.github/actions/test
        with:
          os-name: ${{ matrix.os-name }}
